### ISSUE TITLE
Only compatible with 1:1 ratio

### ISSUE THREAD

**Issue by Botoni** [flowtyone/ComfyUI-Flowty-LDSR#2]
It seems that other resolution ratios than 1:1 results in this black spaces around the image.

1182:886 is the original resolution, a 4:3 ratio for sdxl recommended resolutions. The same happens with 16:9 ratios for example.

![image](https://github.com/flowtyone/ComfyUI-Flowty-LDSR/assets/51716817/38823909-055f-4933-8025-62e062eec943)

**Comment by ltdrdata** [comment]
I also observed the same symptom. 
However, it seems to be not a 1:1 ratio but likely a requirement for multiples of 64.

**Comment by ltdrdata** [comment]
I just made PR.

https://github.com/flowtyone/ComfyUI-Flowty-LDSR/pull/3

**Comment by flowtyone** [comment]
@ltdrdata looks great, thank you! 
Do you mind adding to that pr the updated workflow image?

**Comment by stephantual** [comment]
Weird I hadn't noticed that - good catch! @Botoni !

**Comment by ltdrdata** [comment]
> @ltdrdata looks great, thank you! Do you mind adding to that pr the updated workflow image?

That's OK.

**Comment by flowtyone** [comment]
Merged fix from @ltdrdata ,  closing this issue
