### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by nDman** [flowtyone/ComfyUI-Flowty-LDSR#7]
It generates this error: 
` from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'`

**Comment by corolorn** [comment]
yep its true

**Comment by flowtyone** [comment]
[Duplicate of #4](https://github.com/flowtyone/ComfyUI-Flowty-LDSR/issues/4)
